### ISSUE TITLE
Kanban and React Application setup

### ISSUE THREAD

**Issue by NoelLincoln** [DevKaranJ/space-travelers-hub#26]
Hello 👋,

We have set up our react application and kanban board as recommended.
We are a group of two, my partner is @DevKaranJ 

This is our project https://github.com/DevKaranJ/space-travelers-hub/projects/1

**Comment by zeff96** [comment]
### Status: CHANGES REQUIRED ♻️ ♻️ ♻️ 
Hi @NoelLincoln and @DevKaranJ , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media3.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp?cid=ecf05e47jkz8cxhz4dphch3i08e0bjgype876hba6fpy998n&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
✔️ Cards created

## Required Changes ♻️

- [x] Hello, you are a group of two, thus kindly remove the card with prefix Team3
- [x] Greetings! 🌟 It's important to note that our cards currently lack assignees, making it challenging to determine if the project is being evenly distributed among team members. Please, let's make sure to assign each task to a team member and adhere to our balanced task policy. This way, we can ensure that everyone has a fair share of responsibilities and contributes effectively to the project's success. 🤝💼👩‍💼👨‍💼
- [x] Hello there! 📚✨ To ensure clarity and transparency, please make it a point to include the number of points each student earns for a task within the card title, indicated as [Xpt]. This way, it becomes easier to track and manage the progress and contributions of each student. 📝💯👨‍🎓👩‍🎓

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danmainah** [comment]
Hi @NoelLincoln and @DevKaranJ , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented the change requested to ensure all tasks are assigned
✔️ Implemented the changes requested to ensure all tasks are assigned points and the tasks are evenly distributed among team members.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
